baseURL = 'https://envoss11.github.io'
languageCode = 'en-us'
title = 'eric voss'
theme = 'holy'
publishDir = "docs"

[menu]

  [[menu.main]]
    identifier = "project_portfolio"
    name = "projects"
    url = "/project_portfolio/"
    weight = 2
  [[menu.main]]
    identifier = "stuff"
    name = "stuff i'm thinking about"
    url = "/stuff/"
    weight = 3

[taxonomies]
category = "categories"
tag = "tags"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
