languageCode: en-us
baseURL: "https://envoss11.github.io"
title: Eric Voss

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "I'm a Lead Data Scientist with 10 years of experience in insurance and financial services. My background spans traditional statistical modeling to modern AI deployment, with recent focus on putting generative AI systems into production at scale."
    author: Eric Voss
    intro: "a Lead Data Scientist and AI technical leader."

    defaultTheme: light
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: false


    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        disableHLJS: true
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    #     keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true

menu:
  main:
    - identifier: blog
      name: Blog
      url: /posts
      weight: 10
    - identifier: resume
      name: About Me
      url: /resume
      weight: 20
