# The whole interface to this site. Run `make` on its own for the list.
#
# Everything goes through `bundle exec`, so what runs locally is what
# Gemfile.lock pins, which is what .github/workflows/deploy.yml runs too.

BUNDLE := bundle exec
DATE   := $(shell date +%Y-%m-%d)

# marimo drives the notebook half. `uv run` resolves it from pyproject.toml and
# repairs the environment on the way, so there is no activate step to forget.
# Override it (MARIMO=path/to/marimo) on a machine without uv.
MARIMO ?= uv run --quiet marimo
SYNC   := MARIMO="$(MARIMO)" python3 _bin/sync-notebook.py
NOTEBOOKS := $(wildcard _notebooks/*.py)

# Title -> filename slug: lowercase, non-alphanumerics collapse to one dash,
# no leading or trailing dash. Matches the shape of the URLs already published.
SLUG := $(shell printf '%s' '$(TITLE)' | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$$//')

.DEFAULT_GOAL := help
.PHONY: help serve build check draft wip notebook edit run sync fix notebooks publish

help: ## Show this list
	@echo "usage: make <target>"
	@echo
	@grep -E '^[a-z-]+:.*?## ' $(MAKEFILE_LIST) \
	  | sed -E 's/^([a-z-]+):.*## /  \1|/' \
	  | awk -F'|' '{ printf "  %-11s %s\n", $$1, $$2 }'
	@echo
	@echo '  make notebook TITLE="A question with a number at the end of it"'
	@echo '  make draft    TITLE="Some post title"'
	@echo '  make wip      TITLE="An essay to think about in public"'
	@echo '  make edit SLUG=some-slug'
	@echo '  make sync SLUG=some-slug'
	@echo '  make publish SLUG=some-slug'

serve: ## Preview at localhost:4000, drafts included, reloading on save
	$(BUNDLE) jekyll serve --drafts --livereload --incremental

build: ## Production build into _site/
	JEKYLL_ENV=production $(BUNDLE) jekyll build

check: notebooks build ## Everything CI gates on: notebooks, build, link check
	$(BUNDLE) htmlproofer ./_site --disable-external

# The notebook half of the gate, and the reason it exists: the page body is
# generated, so nothing stops a notebook edit from being committed without the
# page it feeds. Locally that is a stale preview; on master it is a published
# page that disagrees with the notebook under it. --check writes nothing and
# fails if the two have drifted apart.
notebooks: ## Lint the notebooks and prove their pages are in step
ifneq ($(NOTEBOOKS),)
	$(MARIMO) check --strict $(NOTEBOOKS)
	$(SYNC) --check
else
	@echo 'no notebooks yet — nothing to check'
endif

draft: ## Scaffold _drafts/<slug>.md from a title
	@test -n '$(TITLE)' || { echo 'usage: make draft TITLE="Some post title"'; exit 1; }
	@test -n '$(SLUG)'  || { echo 'that title slugifies to nothing — try another'; exit 1; }
	@test ! -f '_drafts/$(SLUG).md' || { echo '_drafts/$(SLUG).md already exists'; exit 1; }
	@mkdir -p _drafts
	@printf '%s\n' \
	  '---' \
	  'title: "$(TITLE)"' \
	  'excerpt: ""' \
	  '# An image is optional. Drop the file in /assets/images/ and point at it here.' \
	  '# image_fit: contain letterboxes charts and screenshots instead of cropping them.' \
	  '# image: /assets/images/example-header.png' \
	  '# image_fit: contain' \
	  'tags_list:' \
	  '  - ""' \
	  '---' \
	  '' \
	  > '_drafts/$(SLUG).md'
	@echo 'wrote _drafts/$(SLUG).md — `make serve` shows it, publishing does not'

# The tier between a draft and a post: live at /posts/wip/<slug>/, but noindex,
# out of the sitemap and out of RSS. The date goes in the front matter here
# rather than the filename — the drawer on /posts/ sorts on it, and a note
# without one falls back to sorting by filename.
wip: ## Scaffold _wip/<slug>.md + _research/<slug>/ — for an essay, no notebook
	@test -n '$(TITLE)' || { echo 'usage: make wip TITLE="Some note title"'; exit 1; }
	@test -n '$(SLUG)'  || { echo 'that title slugifies to nothing — try another'; exit 1; }
	@test ! -f '_wip/$(SLUG).md' || { echo '_wip/$(SLUG).md already exists'; exit 1; }
	@mkdir -p _wip '_research/$(SLUG)'
	@printf '%s\n' \
	  '---' \
	  'title: "$(TITLE)"' \
	  'date: $(DATE)' \
	  'excerpt: ""' \
	  'tags_list:' \
	  '  - ""' \
	  '---' \
	  '' \
	  '## The dump' \
	  '' \
	  '## The question(s)' \
	  '' \
	  '## The data' \
	  '' \
	  '## EDA' \
	  '' \
	  '## Next steps' \
	  '' \
	  > '_wip/$(SLUG).md'
	@printf '%s\n' \
	  '# Working notes for _wip/$(SLUG).md' \
	  '' \
	  'Raw pulls, scripts, and sources. Never built — Jekyll skips _-prefixed dirs.' \
	  > '_research/$(SLUG)/notes.md'
	@echo 'wrote _wip/$(SLUG).md and _research/$(SLUG)/  ->  /posts/wip/$(SLUG)/'

# An exploration is a notebook, and the notebook is the source: the page under
# _wip/ keeps its front matter and has everything below it generated by
# `make sync`. `make wip` above stays for the other shape — an essay, which has
# no data at the bottom of it and no reason to be wrapped in a Python file.
#
# The template lives in the skill directory rather than next to this file
# because a cloud session gets `.claude/` and needs the same starting point.
# One copy, two callers.
notebook: ## Scaffold _notebooks/<slug>.py + its page + _research/<slug>/
	@test -n '$(TITLE)' || { echo 'usage: make notebook TITLE="Some question"'; exit 1; }
	@test -n '$(SLUG)'  || { echo 'that title slugifies to nothing — try another'; exit 1; }
	@test ! -f '_notebooks/$(SLUG).py' || { echo '_notebooks/$(SLUG).py already exists'; exit 1; }
	@test ! -f '_wip/$(SLUG).md' || { echo '_wip/$(SLUG).md already exists'; exit 1; }
	@mkdir -p _notebooks _wip '_research/$(SLUG)'
	@sed 's/^    SLUG = "REPLACE-ME"/    SLUG = "$(SLUG)"/' \
	  .claude/skills/wip-note/notebook-template.py > '_notebooks/$(SLUG).py'
	@printf '%s\n' \
	  '---' \
	  'title: "$(TITLE)"' \
	  'date: $(DATE)' \
	  'excerpt: ""' \
	  'tags_list:' \
	  '  - ""' \
	  '---' \
	  > '_wip/$(SLUG).md'
	@printf '%s\n' \
	  '# Working notes for _notebooks/$(SLUG).py' \
	  '' \
	  'Raw pulls and sources. Never built — Jekyll skips _-prefixed dirs.' \
	  > '_research/$(SLUG)/notes.md'
	@$(SYNC) '$(SLUG)'
	@echo 'now: make edit SLUG=$(SLUG)   ->  /posts/wip/$(SLUG)/'

edit: ## Open a notebook in marimo (--sandbox, for its PEP 723 deps)
	@test -n '$(SLUG)' || { echo 'usage: make edit SLUG=<slug>'; exit 1; }
	@test -f '_notebooks/$(SLUG).py' || { echo 'no such notebook: _notebooks/$(SLUG).py'; exit 1; }
	$(MARIMO) edit --sandbox '_notebooks/$(SLUG).py'

# A marimo notebook is also an ordinary script: cells run in dataflow order, so
# this redraws the figures and re-pulls the data without opening anything.
# `uv run --script` reads the PEP 723 header, which is what makes it one
# command on a machine that has never installed pandas.
run: ## Execute a notebook headless — redraws its figures into assets/images/
	@test -n '$(SLUG)' || { echo 'usage: make run SLUG=<slug>'; exit 1; }
	@test -f '_notebooks/$(SLUG).py' || { echo 'no such notebook: _notebooks/$(SLUG).py'; exit 1; }
	uv run --script '_notebooks/$(SLUG).py'

# Run this after every editing session. The page is a build artifact that
# happens to be committed, so the notebook and the page move together or the
# `notebooks` gate above turns the PR red.
sync: ## Regenerate a note page from its notebook (all of them if no SLUG)
	@$(SYNC) $(SLUG)

fix: ## Apply marimo's own formatting fixes to the notebooks
ifneq ($(NOTEBOOKS),)
	$(MARIMO) check --fix $(NOTEBOOKS)
else
	@echo 'no notebooks yet — nothing to fix'
endif

# One target for both sources. _wip/ is checked first: a slug that exists in
# both is ambiguous and is an error rather than a guess.
publish: ## Move a note out of _wip/ or _drafts/ into _posts/, stamped today
	@test -n '$(SLUG)' || { echo 'usage: make publish SLUG=<slug>'; exit 1; }
	@test ! \( -f '_wip/$(SLUG).md' -a -f '_drafts/$(SLUG).md' \) \
	  || { echo '$(SLUG) exists in both _wip/ and _drafts/ — remove one first'; exit 1; }
	@test -f '_wip/$(SLUG).md' -o -f '_drafts/$(SLUG).md' \
	  || { echo 'no such note: _wip/$(SLUG).md or _drafts/$(SLUG).md'; exit 1; }
	@test ! -f '_posts/$(DATE)-$(SLUG).md' || { echo '_posts/$(DATE)-$(SLUG).md already exists'; exit 1; }
	@src=$$(test -f '_wip/$(SLUG).md' && echo '_wip/$(SLUG).md' || echo '_drafts/$(SLUG).md'); \
	  git mv "$$src" '_posts/$(DATE)-$(SLUG).md' 2>/dev/null \
	    || mv "$$src" '_posts/$(DATE)-$(SLUG).md'; \
	  echo "published $$src  ->  _posts/$(DATE)-$(SLUG).md  ->  /posts/$(SLUG)/"
	@grep -q '^date:' '_posts/$(DATE)-$(SLUG).md' \
	  && echo 'drop the `date:` line from the front matter — the filename carries it now' \
	  || true
